# Capstone 

Filtering data for only patents in US and combining 2009-2019, 2020 was separate. At the time 2021 and beyond not yet availible.

In [23]:
import pandas as pd
import numpy as np

In [24]:
two19 = pd.read_csv('2019.csv')

In [5]:
two19.columns

Index(['patent_number', 'assignee', 'grant_year', 'application_year',
       'application_number', 'country', 'city', 'state', 'county',
       'ipc_section', 'team_size', 'inventors', 'men_inventors',
       'women_inventors', 'inventor_name1', 'male_flag1', 'inventor_id1',
       'inventor_name2', 'male_flag2', 'inventor_id2', 'inventor_name3',
       'male_flag3', 'inventor_id3', 'inventor_name4', 'male_flag4',
       'inventor_id4', 'inventor_name5', 'male_flag5', 'inventor_id5',
       'inventor_name6', 'male_flag6', 'inventor_id6', 'inventor_name7',
       'male_flag7', 'inventor_id7', 'inventor_name8', 'male_flag8',
       'inventor_id8', 'inventor_name9', 'male_flag9', 'inventor_id9'],
      dtype='object')

In [25]:
two19.tail()

,patent_number,assignee,grant_year,application_year,application_number,country,city,state,county,ipc_section,...,inventor_id6,inventor_name7,male_flag7,inventor_id7,inventor_name8,male_flag8,inventor_id8,inventor_name9,male_flag9,inventor_id9
382559,RE47664,APPLE INC.,2019,2017,29622909,US,Cupertino,CA,Santa Clara,NaN,...,fl:s_ln:jobs-3,Duncan Robert Kerr,1.0,fl:d_ln:kerr-1,Shin Nishibori,1.0,fl:s_ln:nishibori-1,Matthew Dean Rohrbach,1.0,fl:m_ln:rohrbach-2
382560,RE47689,F. HOFFMANN-LA ROCHE AG,2019,2017,15695299,CH,Basel,NaN,NaN,A C,...,fl:g_ln:karp-1,Chang-Sun Lee,1.0,fl:c_ln:lee-793,Chunshi Li,NaN,fl:c_ln:li-215,Jana Narasimhan,0.0,fl:j_ln:narasimhan-1
382561,RE47746,"RUSOH, INC.",2019,2018,29651249,US,Eau Claire,WI,Eau Claire,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
382562,RE47782,TAIWAN SEMICONDUCTOR MANUFACTURING COMPANY LTD.,2019,2016,15392532,TW,Hsinchu,NaN,NaN,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
382563,RE47788,KABUSHIKI KAISHA TOSHIBA,2019,2018,16025680,JP,Tokyo,NaN,NaN,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
two19['country'].unique()

array(['IT', 'US', 'CN', 'JP', 'CA', 'DE', 'NL', 'GB', 'DK', 'FR', 'CH',
       'HK', 'KR', 'LU', 'TW', 'AU', 'VG', 'SG', 'IL', 'SE', 'IE', 'BE',
       'BB', 'ES', 'AT', 'BM', 'MY', 'FI', 'IN', 'NO', 'LT', 'TR', 'MT',
       'LI', nan, 'SA', 'BR', 'NZ', 'ZA', 'MX', 'IR', 'MO', 'TH', 'PL',
       'CZ', 'HU', 'KY', 'UA', 'RU', 'CY', 'ID', 'DO', 'BS', 'GR', 'CO',
       'QA', 'CL', 'LV', 'VN', 'EG', 'AE', 'SC', 'CR', 'PT', 'EE', 'IS',
       'GI', 'WS', 'IM', 'KW', 'SK', 'MC', 'JE', 'AN', 'RS', 'SI', 'LK',
       'un', 'PE', 'AR', 'AD', 'PH', 'JO', 'CU', 'CK', 'UY', 'AI', 'MU',
       'BG', 'BZ', 'KZ', 'TT', 'LB', 'BN', 'HR', 'CW', 'VE', 'BY', 'PK',
       'BD', 'PA', 'RO', 'UK', 'GG', 'ML', 'TN', 'MH', 'OM', 'DM', 'DD',
       'EC', 'NI', 'JM', 'SM', 'KP', 'KN', 'JA', 'DL', 'CS', 'MR', 'FO',
       'TK', 'BO', 'KH', 'MD'], dtype=object)

In [28]:
two19[two19['country'].isna()]

,patent_number,assignee,grant_year,application_year,application_number,country,city,state,county,ipc_section,...,inventor_id6,inventor_name7,male_flag7,inventor_id7,inventor_name8,male_flag8,inventor_id8,inventor_name9,male_flag9,inventor_id9
598,10166417,SCOTT HEALTH & SAFETY LTD.,2019,2015,14797933,NaN,NaN,NaN,NaN,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
923,10166785,"CHARTA GROUP, INC",2019,2017,15427173,NaN,NaN,NaN,NaN,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2042,10167993,"OCEANEERING INTERNATIONAL, INC.",2019,2018,15945744,NaN,NaN,NaN,NaN,B F G,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3813,10169832,"INSTANT ACCESS NETWORKS, LLC",2019,2013,13889867,NaN,NaN,NaN,NaN,G H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4306,10170350,"NAURA AKRION, INC.",2019,2015,14703459,NaN,NaN,NaN,NaN,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377167,D865147,"KINGKAR ECO-TECHNOLOGIES CO., LTD.",2019,2017,29604999,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
377943,D866092,"SHANGHAI QINXU INDUSTRY CO., LTD.",2019,2017,29623031,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
379227,D867688,DELCA CORPORATION,2019,2018,29656940,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
380557,D869329,GARANT GP,2019,2018,29647996,NaN,Saint-FranÃ§ois-de-la-RiviÃ¨re-du-Sud,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
382007,D871093,"MUTSUMI GIKEN CO., LTD.",2019,2017,35505159,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
two19[two19['country'] == 'US']

,patent_number,assignee,grant_year,application_year,application_number,country,city,state,county,ipc_section,...,inventor_id6,inventor_name7,male_flag7,inventor_id7,inventor_name8,male_flag8,inventor_id8,inventor_name9,male_flag9,inventor_id9
1,10165722,DEERE & COMPANY,2019,2015,14921217,US,Moline,IL,Rock Island,A G,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10165723,BAYER CROPSCIENCE LP,2019,2014,14309563,US,Research Triangle Park,NC,NaN,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10165724,"CRARY INDUSTRIES, INC.",2019,2016,15360099,US,West Fargo,ND,Cass,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10165725,DEERE & COMPANY,2019,2016,15281867,US,Moline,IL,Rock Island,A B G,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,10165726,CNH INDUSTRIAL AMERICA LLC,2019,2016,15389664,US,New Holland,PA,Lancaster,A,...,fl:c_ln:roberts-44,James F. Rayfield,1.0,fl:j_ln:rayfield-5,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
382550,RE47549,"S.R. SMITH, LLC",2019,2015,29515597,US,Canby,OR,Clackamas,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
382554,RE47572,"THE CHARLES MACHINE WORKS, INC.",2019,2018,29655614,US,Perry,OK,Noble,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
382558,RE47657,"TOSHIBA AMERICA BUSINESS SOLUTIONS, INC.",2019,2017,15845923,US,Lake Forest,CA,Orange,G,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
382559,RE47664,APPLE INC.,2019,2017,29622909,US,Cupertino,CA,Santa Clara,NaN,...,fl:s_ln:jobs-3,Duncan Robert Kerr,1.0,fl:d_ln:kerr-1,Shin Nishibori,1.0,fl:s_ln:nishibori-1,Matthew Dean Rohrbach,1.0,fl:m_ln:rohrbach-2
382561,RE47746,"RUSOH, INC.",2019,2018,29651249,US,Eau Claire,WI,Eau Claire,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
two18 = pd.read_csv('2018.csv')
sum(two18['country'].isna())

469

In [4]:
df = pd.DataFrame()

#works on one but not many ? 
def read_filter(file_name):
    new = pd.read_csv(str(file_name)+'.csv')
    new = new[new['country'] == 'US']
    #df2 = df.append(new)
    return new

In [3]:
read_filter(2019)

/var/folders/8w/lcbkp3d94ms0tyj03qhvhby40000gn/T/ipykernel_69669/3902920134.py:1: DtypeWarning: Columns (0,9) have mixed types.Specify dtype option on import or set low_memory=False.
  read_filter(2019)

,patent_number,assignee,grant_year,application_year,application_number,country,city,state,county,ipc_section,...,inventor_id6,inventor_name7,male_flag7,inventor_id7,inventor_name8,male_flag8,inventor_id8,inventor_name9,male_flag9,inventor_id9
1,10165722,DEERE & COMPANY,2019,2015,14921217,US,Moline,IL,Rock Island,A G,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10165723,BAYER CROPSCIENCE LP,2019,2014,14309563,US,Research Triangle Park,NC,NaN,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10165724,"CRARY INDUSTRIES, INC.",2019,2016,15360099,US,West Fargo,ND,Cass,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10165725,DEERE & COMPANY,2019,2016,15281867,US,Moline,IL,Rock Island,A B G,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,10165726,CNH INDUSTRIAL AMERICA LLC,2019,2016,15389664,US,New Holland,PA,Lancaster,A,...,fl:c_ln:roberts-44,James F. Rayfield,1.0,fl:j_ln:rayfield-5,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
382550,RE47549,"S.R. SMITH, LLC",2019,2015,29515597,US,Canby,OR,Clackamas,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
382554,RE47572,"THE CHARLES MACHINE WORKS, INC.",2019,2018,29655614,US,Perry,OK,Noble,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
382558,RE47657,"TOSHIBA AMERICA BUSINESS SOLUTIONS, INC.",2019,2017,15845923,US,Lake Forest,CA,Orange,G,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
382559,RE47664,APPLE INC.,2019,2017,29622909,US,Cupertino,CA,Santa Clara,NaN,...,fl:s_ln:jobs-3,Duncan Robert Kerr,1.0,fl:d_ln:kerr-1,Shin Nishibori,1.0,fl:s_ln:nishibori-1,Matthew Dean Rohrbach,1.0,fl:m_ln:rohrbach-2
382561,RE47746,"RUSOH, INC.",2019,2018,29651249,US,Eau Claire,WI,Eau Claire,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
for i in range(2009, 2020, 1):
    print(i)

2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019

In [45]:
for i in range(2009, 2019, 1):
    read_filter(i)

/var/folders/8w/lcbkp3d94ms0tyj03qhvhby40000gn/T/ipykernel_67676/1301831092.py:2: DtypeWarning: Columns (0,9) have mixed types.Specify dtype option on import or set low_memory=False.
  read_filter(i)
/var/folders/8w/lcbkp3d94ms0tyj03qhvhby40000gn/T/ipykernel_67676/1301831092.py:2: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  read_filter(i)

In [ ]:
#killed the kernal
df = pd.DataFrame()
for i in range(2009, 2020):
    dfi = read_filter(i)
    df = df.append(dfi)

/var/folders/8w/lcbkp3d94ms0tyj03qhvhby40000gn/T/ipykernel_69669/1911723640.py:3: DtypeWarning: Columns (0,9) have mixed types.Specify dtype option on import or set low_memory=False.
  dfi = read_filter(i)
/var/folders/8w/lcbkp3d94ms0tyj03qhvhby40000gn/T/ipykernel_69669/1911723640.py:3: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  dfi = read_filter(i)

In [56]:
#df.sort_values('grant_year', ascending = False )

,patent_number,assignee,grant_year,application_year,application_number,country,city,state,county,ipc_section,...,inventor_id6,inventor_name7,male_flag7,inventor_id7,inventor_name8,male_flag8,inventor_id8,inventor_name9,male_flag9,inventor_id9
1,10165722,DEERE & COMPANY,2019,2015,14921217,US,Moline,IL,Rock Island,A G,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124998,10299047,"MEYER SOUND LABORATORIES, INCORPORATED",2019,2017,15693319,US,Berkeley,CA,Alameda,A H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124992,10299040,"DTS, INC.",2019,2017,15811353,US,Calabasas,CA,Los Angeles,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124991,10299039,APPLE INC.,2019,2017,15613049,US,Cupertino,CA,Santa Clara,G H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124990,10299038,BOSE CORPORATION,2019,2018,16107464,US,Framingham,MA,Middlesex,A G H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
248345,10430240,PALANTIR TECHNOLOGIES INC.,2019,2016,15284959,US,Palo Alto,CA,Santa Clara,G H,...,fl:b_ln:toth-3,David Tolnay,1.0,fl:d_ln:tolnay-2,Daniel Rothfus,1.0,fl:d_ln:rothfus-1,Bradley Moylan,1.0,fl:b_ln:moylan-1
248344,10430239,CLARI INC.,2019,2016,15246513,US,Sunnyvale,CA,Santa Clara,G,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
248343,10430238,"CAPITAL ONE SERVICES, LLC",2019,2019,16426548,US,McLean,VA,Fairfax,G,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
248339,10430234,"RED HAT, INC.",2019,2016,15044913,US,Raleigh,NC,Wake,G,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
382561,RE47746,"RUSOH, INC.",2019,2018,29651249,US,Eau Claire,WI,Eau Claire,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df2009 = read_filter(2009)
df2010 = read_filter(2010)
df2011 = read_filter(2011)
df2012 = read_filter(2012)
df2013 = read_filter(2013)
df2014 = read_filter(2014)
df2015 = read_filter(2015)
df2016 = read_filter(2016)
df2017 = read_filter(2017)
df2018 = read_filter(2018)
df2019 = read_filter(2019)

/var/folders/8w/lcbkp3d94ms0tyj03qhvhby40000gn/T/ipykernel_69774/1727663658.py:1: DtypeWarning: Columns (0,9) have mixed types.Specify dtype option on import or set low_memory=False.
  df2009 = read_filter(2009)
/var/folders/8w/lcbkp3d94ms0tyj03qhvhby40000gn/T/ipykernel_69774/1727663658.py:2: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  df2010 = read_filter(2010)
/var/folders/8w/lcbkp3d94ms0tyj03qhvhby40000gn/T/ipykernel_69774/1727663658.py:3: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  df2011 = read_filter(2011)
/var/folders/8w/lcbkp3d94ms0tyj03qhvhby40000gn/T/ipykernel_69774/1727663658.py:4: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  df2012 = read_filter(2012)
/var/folders/8w/lcbkp3d94ms0tyj03qhvhby40000gn/T/ipykernel_69774/1727663658.py:5: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  df2013 = read_filter(2013)
/var/folders/8w/lcbkp3d94ms0tyj03qhvhby40000gn/T/ipykernel_69774/1727663658.py:6: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  df2014 = read_filter(2014)
/var/folders/8w/lcbkp3d94ms0tyj03qhvhby40000gn/T/ipykernel_69774/1727663658.py:7: DtypeWarning: Columns (0,9) have mixed types.Specify dtype option on import or set low_memory=False.
  df2015 = read_filter(2015)
/var/folders/8w/lcbkp3d94ms0tyj03qhvhby40000gn/T/ipykernel_69774/1727663658.py:8: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  df2016 = read_filter(2016)
/var/folders/8w/lcbkp3d94ms0tyj03qhvhby40000gn/T/ipykernel_69774/1727663658.py:9: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  df2017 = read_filter(2017)
/var/folders/8w/lcbkp3d94ms0tyj03qhvhby40000gn/T/ipykernel_69774/1727663658.py:10: DtypeWarning: Columns (0,9) have mixed types.Specify dtype option on import or set low_memory=False.
  df2018 = read_filter(2018)
/var/folders/8w/lcbkp3d94ms0tyj03qhvhby40000gn/T/ipykernel_69774/1727663658.py:11: DtypeWarning: Columns (0,9) have mixed types.Specify dtype option on import or set low_memory=False.
  df2019 = read_filter(2019)

In [8]:
#default behavior limits the number of rows/columns you can see
#turn that off

pd.set_option('display.max_columns', None)

In [7]:
dfall = pd.concat([df2009, df2010, df2011, df2012, df2013, 
                   df2014, df2015, df2016, df2017, df2018, df2019])

,patent_number,assignee,grant_year,application_year,application_number,country,city,state,county,ipc_section,...,inventor_id6,inventor_name7,male_flag7,inventor_id7,inventor_name8,male_flag8,inventor_id8,inventor_name9,male_flag9,inventor_id9
382561,RE47746,"RUSOH, INC.",2019,2018,29651249,US,Eau Claire,WI,Eau Claire,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124951,10298995,DISH NETWORK L.L.C.,2019,2017,15859153,US,Englewood,CO,Arapahoe,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124984,10299032,APPLE INC.,2019,2017,15701335,US,Cupertino,CA,Santa Clara,H,...,fl:o_ln:ilkorur-1,Thomas H. Tsang,1.0,fl:t_ln:tsang-9,NaN,NaN,NaN,NaN,NaN,NaN
124983,10299031,BOSE CORPORATION,2019,2018,15884924,US,Framingham,MA,Middlesex,G H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124981,10299029,APPLE INC.,2019,2018,16108856,US,Cupertino,CA,Santa Clara,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118767,7600532,INGERSOLL-RAND COMPANY,2009,2006,11591156,US,Montvale,NJ,Bergen,F,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118768,7600533,CALIFORNIA INSTITUTE OF TECHNOLOGY,2009,2007,11837450,US,Pasadena,CA,Los Angeles,F,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118769,7600534,SCHLUMBERGER TECHNOLOGY CORPORATION,2009,2004,10958438,US,Sugar Land,TX,Fort Bend,E F,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118771,7600537,HONEYWELL INTERNATIONAL INC.,2009,2005,11228935,US,Morristown,NJ,Morris,F,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,7472428,"NIKE, INC.",2009,2004,10814594,US,Beaverton,OR,Washington,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
dfall.sort_values('grant_year', ascending = False )

,patent_number,assignee,grant_year,application_year,application_number,country,city,state,county,ipc_section,team_size,inventors,men_inventors,women_inventors,inventor_name1,male_flag1,inventor_id1,inventor_name2,male_flag2,inventor_id2,inventor_name3,male_flag3,inventor_id3,inventor_name4,male_flag4,inventor_id4,inventor_name5,male_flag5,inventor_id5,inventor_name6,male_flag6,inventor_id6,inventor_name7,male_flag7,inventor_id7,inventor_name8,male_flag8,inventor_id8,inventor_name9,male_flag9,inventor_id9
382561,RE47746,"RUSOH, INC.",2019,2018,29651249,US,Eau Claire,WI,Eau Claire,NaN,4,4,4,0,Justun Seymour,1.0,fl:j_ln:seymour-6,Ryan Barrows,1.0,fl:r_ln:barrows-4,Seth Rooney,1.0,fl:s_ln:rooney-7,Randy Frank Rousseau,1.0,fl:r_ln:rousseau-7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124951,10298995,DISH NETWORK L.L.C.,2019,2017,15859153,US,Englewood,CO,Arapahoe,H,1,1,1,0,Joshua Stumbo,1.0,fl:j_ln:stumbo-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124984,10299032,APPLE INC.,2019,2017,15701335,US,Cupertino,CA,Santa Clara,H,7,6,6,0,Anthony P. Grazian,1.0,fl:a_ln:grazian-1,Christopher Wilk,1.0,fl:c_ln:wilk-2,Claudio Notarangelo,1.0,fl:c_ln:notarangelo-1,Hongdan Tao,NaN,fl:h_ln:tao-12,Michael J. Newman,1.0,fl:m_ln:newman-29,Onur I. Ilkorur,1.0,fl:o_ln:ilkorur-1,Thomas H. Tsang,1.0,fl:t_ln:tsang-9,NaN,NaN,NaN,NaN,NaN,NaN
124983,10299031,BOSE CORPORATION,2019,2018,15884924,US,Framingham,MA,Middlesex,G H,4,4,4,0,Ray Scott Wakeland,1.0,fl:r_ln:wakeland-2,Ryan C. Struzik,1.0,fl:r_ln:struzik-1,Chester S. Williams,1.0,fl:c_ln:williams-2,Jason D. Silver,1.0,fl:j_ln:silver-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124981,10299029,APPLE INC.,2019,2018,16108856,US,Cupertino,CA,Santa Clara,H,1,1,1,0,Jonathan S. Aase,1.0,fl:j_ln:aase-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118767,7600532,INGERSOLL-RAND COMPANY,2009,2006,11591156,US,Montvale,NJ,Bergen,F,2,2,2,0,Thomas R. Headley,1.0,fl:t_ln:headley-1,Lloyd I. Towne,1.0,fl:l_ln:towne-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118768,7600533,CALIFORNIA INSTITUTE OF TECHNOLOGY,2009,2007,11837450,US,Pasadena,CA,Los Angeles,F,4,3,2,1,Yu-Chong Tai,0.0,fl:y_ln:tai-18,Po-Jui Chen,NaN,fl:p_ln:chen-120,Damien C. Rodger,1.0,fl:d_ln:rodger-1,Mark S. Humayun,1.0,fl:m_ln:humayun-2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118769,7600534,SCHLUMBERGER TECHNOLOGY CORPORATION,2009,2004,10958438,US,Sugar Land,TX,Fort Bend,E F,1,1,1,0,Tomas Michael Deaton,1.0,fl:t_ln:deaton-2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118771,7600537,HONEYWELL INTERNATIONAL INC.,2009,2005,11228935,US,Morristown,NJ,Morris,F,4,4,3,1,Ashok Bhatnagar,1.0,fl:a_ln:bhatnagar-26,Lori L. Wagner,0.0,fl:l_ln:wagner-6,Brian D. Arvidson,1.0,fl:b_ln:arvidson-1,Timothy Swinger,1.0,fl:t_ln:swinger-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,7472428,"NIKE, INC.",2009,2004,10814594,US,Beaverton,OR,Washington,A,2,2,2,0,Dylan S. Van Atta,1.0,fl:d_ln:van atta-2,Robert Bruce,1.0,fl:r_ln:bruce-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
dfall.to_csv("2009_2019.csv")

In [11]:
df2020 = read_filter(2020)

/var/folders/8w/lcbkp3d94ms0tyj03qhvhby40000gn/T/ipykernel_69774/4130591173.py:1: DtypeWarning: Columns (0,9) have mixed types.Specify dtype option on import or set low_memory=False.
  df2020 = read_filter(2020)

In [13]:
df2020.to_csv("2020.csv")